// <auto-generated />
using System;
using LakseBot.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.EntityFrameworkCore.Migrations;

namespace LakseBot.Migrations
{
    [DbContext(typeof(MagicLeagueContext))]
    [Migration("20180501174809_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.0-preview2-30571");

            modelBuilder.Entity("LakseBot.Models.MatchResult", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("LoserName");

                    b.Property<int>("RatingChange");

                    b.Property<DateTime>("Timestamp");

                    b.Property<string>("WinnerName");

                    b.HasKey("ID");

                    b.HasIndex("LoserName");

                    b.HasIndex("WinnerName");

                    b.ToTable("MatchResults");
                });

            modelBuilder.Entity("LakseBot.Models.Player", b =>
                {
                    b.Property<string>("Name")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Rating");

                    b.HasKey("Name");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("LakseBot.Models.MatchResult", b =>
                {
                    b.HasOne("LakseBot.Models.Player", "Loser")
                        .WithMany()
                        .HasForeignKey("LoserName");

                    b.HasOne("LakseBot.Models.Player", "Winner")
                        .WithMany()
                        .HasForeignKey("WinnerName");
                });
#pragma warning restore 612, 618
        }
    }
}
